name: smartcourt_portal
description: "SmartCourt AI — Fuqaro portali (mobil). Web fuqaro portalining to'liq nusxasi."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
