const phraseMaps = {
  en: {
    'O‘zbekiston sud tizimi uchun AI ekotizimi':
      'AI ecosystem for the judicial system of Uzbekistan',
    'Insonparvar adolat, soniyalar ichida.': 'Human-centered justice, in seconds.',
    Muammolar: 'Problems',
    'Sud tizimidagi inqirozli nuqtalar': 'Critical points in the judicial system',
    'Muammo aniq: adolatga vaqt yetmayapti.':
      'The problem is clear: justice is running out of time.',
    'Asosiy muammolar': 'Key problems',
    'Global tendensiyalar': 'Global trends',
    'Yuklama tafsilotlari': 'Workload details',
    'SmartCourt AI nimani hal qiladi?': 'What does SmartCourt AI solve?',
    'Adolat. Tezroq. Aniqroq.': 'Justice. Faster. More precise.',
    'Fuqaro portali': 'Citizen portal',
    'Sudya paneli': 'Judge workspace',
    'Admin panel': 'Admin panel',
    'Nazorat va ijro': 'Oversight and execution',
    'Nazorat/Ijro': 'Oversight/Execution',
    'Asosiy navigatsiya': 'Main navigation',
    'Mobil navigatsiya': 'Mobile navigation',
    'Ishlar va AI': 'Cases and AI',
    Asosiy: 'Main',
    Chiqish: 'Sign out',
    'Sessiya yopildi.': 'Session closed.',
    'Bosh sahifaga qaytish': 'Return to home',
    'Tizimga kirish': 'Sign in',
    'Demo ko‘rish': 'View demo',
    "Demo ko'rish": 'View demo',
    Batafsil: 'Learn more',
    'Ma’lumotlar': 'Information',
    Jadval: 'Table',
    'Vaqt jadvali': 'Timeline',
    'Yon panel': 'Side panel',
    'Yangi ariza': 'New claim',
    Arizalarim: 'My claims',
    'AI Maslahatchi': 'AI Assistant',
    Sozlamalar: 'Settings',
    Xabarlar: 'Messages',
    Kutubxona: 'Library',
    Profil: 'Profile',
    Dashboard: 'Dashboard',
    'Jonli majlis': 'Live hearing',
    Pretsedentlar: 'Precedents',
    Kalendar: 'Calendar',
    Statistika: 'Statistics',
    Foydalanuvchilar: 'Users',
    Sudlar: 'Courts',
    'AI modellari': 'AI models',
    'Aqlli kantselyariya': 'Smart registry office',
    'Arizani sudga yuborishdan oldin tekshiring.': 'Check the claim before submitting it to court.',
    'Kiruvchi oqim va filtrlash': 'Incoming flow and filtering',
    'Ariza manbasi': 'Claim source',
    'PDF yoki erkin matn': 'PDF or free text',
    'PDF arizani yuklash': 'Upload PDF claim',
    'Ariza matni': 'Claim text',
    'Arizani tahlil qilish': 'Analyze claim',
    'Tahlil qilinmoqda...': 'Analyzing...',
    'ClaimValidator natijasi': 'ClaimValidator result',
    'Ariza tayyorlik darajasi': 'Claim readiness score',
    Yurisdiksiya: 'Jurisdiction',
    'Nizo turi': 'Dispute type',
    'Topilgan huquqiy faktlar': 'Detected legal facts',
    'Tuzatilishi kerak': 'Needs correction',
    'Mashina o‘qiydigan natija': 'Machine-readable result',
    'Ariza wizardiga o‘tish': 'Go to claim wizard',
    'ClaimValidator xulosasi': 'ClaimValidator summary',
    'Qarorlarni avtomatik ijro etish': 'Automatic enforcement of decisions',
    'Qarorni inson omilisiz ijroga yuboring.':
      'Send the decision for enforcement without manual steps.',
    'Xavfsizlik, shaffoflik va yakuniy ijro': 'Security, transparency, and final enforcement',
    'AutoExec ishga tushirish': 'Start AutoExec',
    'Ijro qilinmoqda...': 'Enforcing...',
    'Qayta boshlash': 'Restart',
    'Bajarilgan integratsiya bosqichlari': 'Completed integration steps',
    'Ijro ma’lumotlari': 'Enforcement information',
    Mediatsiya: 'Mediation',
    'Mediatsiya markazi': 'Mediation center',
    'Mediatsiya boshlash': 'Start mediation',
    'Mediatsiya sessiyasi': 'Mediation session',
    'Mediatsiya kelishuvi': 'Mediation agreement',
    'Mediatsiya tavsiya qilindi': 'Mediation recommended',
    'Sudgacha kelishuv takliflari, sessiyalar va muvaffaqiyat ehtimoli.':
      'Pre-court settlement proposals, sessions, and success probability.',
    'Mehnat nizosi': 'Labor dispute',
    'Oilaviy nizosi': 'Family dispute',
    'Iqtisodiy nizosi': 'Economic dispute',
    '67% muvaffaqiyat ehtimoli.': '67% success probability.',
    'Tomonlar kelishuvga taklif qilingan.': 'The parties have been invited to settle.',
    'Mediator tayinlanmoqda.': 'A mediator is being assigned.',
    'Tomonlar, mediator va kelishuv bandlari bilan jonli sessiya.':
      'Live session with the parties, mediator, and settlement terms.',
    'Audit log': 'Audit log',
    Integratsiyalar: 'Integrations',
    Qarorlar: 'Decisions',
    'Ijro nazorati': 'Execution oversight',
    'Aloqalar grafi': 'Relationship graph',
    Hisobotlar: 'Reports',
    Bildirishnoma: 'Notifications',
    Bildirishnomalar: 'Notifications',
    Qidirish: 'Search',
    'Til tanlash': 'Select language',
    Menyu: 'Menu',
    Saqlash: 'Save',
    Yuborish: 'Submit',
    Eksport: 'Export',
    Tozalash: 'Clear',
    Filter: 'Filter',
    'Qoralama saqlash': 'Save draft',
    'Bekor qilish': 'Cancel',
    'Davom etish': 'Continue',
    Orqaga: 'Back',
    Keyingi: 'Next',
    Tugatish: 'Finish',
    'O‘tkazib yuborish': 'Skip',
    'Bo‘sh ro‘yxat': 'Empty list',
    'Eksport formatini tanlang': 'Choose export format',
    'Tafsilot drawer': 'Details',
    'Jadvaldan qidirish': 'Search table',
    'ta yozuv': 'records',
    'Filterlarni tozalash': 'Clear filters',
    'Ma’lumot saqlandi': 'Information saved',
    'Amal bajarildi': 'Action completed',
    'Demo ma’lumotlar yangilandi.': 'Demo data has been updated.',
    'Forma tozalandi': 'Form cleared',
    'Kiritilgan qiymatlar tozalandi.': 'Entered values were cleared.',
    'Eksport tayyor': 'Export ready',
    'Fayl yuklab olindi.': 'The file has been downloaded.',
    'Til almashtirildi': 'Language changed',
    'rejimi yoqildi.': 'mode enabled.',
    'Yangi xabar': 'New message',
    'Majlis sanasi': 'Hearing date',
    'To‘lov holati': 'Payment status',
    'Davlat boji tasdiqlandi.': 'The state fee has been confirmed.',
    'Global qidiruv oynasi tayyorlanmoqda.': 'Global search is being prepared.',
    'Tezkor komandalar paneli ochiladi.': 'The command palette will open.'
  },
  ru: {
    'O‘zbekiston sud tizimi uchun AI ekotizimi': 'ИИ-экосистема для судебной системы Узбекистана',
    'Insonparvar adolat, soniyalar ichida.': 'Гуманное правосудие за считанные секунды.',
    Muammolar: 'Проблемы',
    'Sud tizimidagi inqirozli nuqtalar': 'Критические точки судебной системы',
    'Muammo aniq: adolatga vaqt yetmayapti.': 'Проблема ясна: правосудию не хватает времени.',
    'Asosiy muammolar': 'Основные проблемы',
    'Global tendensiyalar': 'Глобальные тенденции',
    'Yuklama tafsilotlari': 'Подробности нагрузки',
    'SmartCourt AI nimani hal qiladi?': 'Что решает SmartCourt AI?',
    'Adolat. Tezroq. Aniqroq.': 'Правосудие. Быстрее. Точнее.',
    'Fuqaro portali': 'Портал гражданина',
    'Sudya paneli': 'Рабочее место судьи',
    'Admin panel': 'Панель администратора',
    'Nazorat va ijro': 'Контроль и исполнение',
    'Nazorat/Ijro': 'Контроль/Исполнение',
    'Asosiy navigatsiya': 'Основная навигация',
    'Mobil navigatsiya': 'Мобильная навигация',
    'Ishlar va AI': 'Дела и ИИ',
    Asosiy: 'Главное',
    Chiqish: 'Выйти',
    'Sessiya yopildi.': 'Сессия завершена.',
    'Bosh sahifaga qaytish': 'Вернуться на главную',
    'Tizimga kirish': 'Войти',
    'Demo ko‘rish': 'Смотреть демо',
    "Demo ko'rish": 'Смотреть демо',
    Batafsil: 'Подробнее',
    'Ma’lumotlar': 'Данные',
    Jadval: 'Таблица',
    'Vaqt jadvali': 'Хронология',
    'Yon panel': 'Боковая панель',
    'Yangi ariza': 'Новое заявление',
    Arizalarim: 'Мои заявления',
    'AI Maslahatchi': 'ИИ-помощник',
    Sozlamalar: 'Настройки',
    Xabarlar: 'Сообщения',
    Kutubxona: 'Библиотека',
    Profil: 'Профиль',
    Dashboard: 'Обзор',
    'Jonli majlis': 'Онлайн-заседание',
    Pretsedentlar: 'Прецеденты',
    Kalendar: 'Календарь',
    Statistika: 'Статистика',
    Foydalanuvchilar: 'Пользователи',
    Sudlar: 'Суды',
    'AI modellari': 'ИИ-модели',
    'Aqlli kantselyariya': 'Умная канцелярия',
    'Arizani sudga yuborishdan oldin tekshiring.': 'Проверьте заявление перед отправкой в суд.',
    'Kiruvchi oqim va filtrlash': 'Входящий поток и фильтрация',
    'Ariza manbasi': 'Источник заявления',
    'PDF yoki erkin matn': 'PDF или свободный текст',
    'PDF arizani yuklash': 'Загрузить PDF-заявление',
    'Ariza matni': 'Текст заявления',
    'Arizani tahlil qilish': 'Проанализировать заявление',
    'Tahlil qilinmoqda...': 'Идёт анализ...',
    'ClaimValidator natijasi': 'Результат ClaimValidator',
    'Ariza tayyorlik darajasi': 'Готовность заявления',
    Yurisdiksiya: 'Юрисдикция',
    'Nizo turi': 'Тип спора',
    'Topilgan huquqiy faktlar': 'Найденные юридические факты',
    'Tuzatilishi kerak': 'Требуется исправить',
    'Mashina o‘qiydigan natija': 'Машиночитаемый результат',
    'Ariza wizardiga o‘tish': 'Перейти к мастеру заявления',
    'ClaimValidator xulosasi': 'Заключение ClaimValidator',
    'Qarorlarni avtomatik ijro etish': 'Автоматическое исполнение решений',
    'Qarorni inson omilisiz ijroga yuboring.':
      'Отправьте решение на исполнение без ручных действий.',
    'Xavfsizlik, shaffoflik va yakuniy ijro': 'Безопасность, прозрачность и итоговое исполнение',
    'AutoExec ishga tushirish': 'Запустить AutoExec',
    'Ijro qilinmoqda...': 'Исполнение...',
    'Qayta boshlash': 'Перезапустить',
    'Bajarilgan integratsiya bosqichlari': 'Завершённые этапы интеграции',
    'Ijro ma’lumotlari': 'Данные исполнения',
    Mediatsiya: 'Медиация',
    'Mediatsiya markazi': 'Центр медиации',
    'Mediatsiya boshlash': 'Начать медиацию',
    'Mediatsiya sessiyasi': 'Сессия медиации',
    'Mediatsiya kelishuvi': 'Медиативное соглашение',
    'Mediatsiya tavsiya qilindi': 'Рекомендована медиация',
    'Sudgacha kelishuv takliflari, sessiyalar va muvaffaqiyat ehtimoli.':
      'Предложения по досудебному урегулированию, сессии и вероятность успеха.',
    'Mehnat nizosi': 'Трудовой спор',
    'Oilaviy nizosi': 'Семейный спор',
    'Iqtisodiy nizosi': 'Экономический спор',
    '67% muvaffaqiyat ehtimoli.': 'Вероятность успеха 67%.',
    'Tomonlar kelishuvga taklif qilingan.': 'Стороны приглашены к урегулированию.',
    'Mediator tayinlanmoqda.': 'Назначается медиатор.',
    'Tomonlar, mediator va kelishuv bandlari bilan jonli sessiya.':
      'Онлайн-сессия со сторонами, медиатором и условиями соглашения.',
    'Audit log': 'Журнал аудита',
    Integratsiyalar: 'Интеграции',
    Qarorlar: 'Решения',
    'Ijro nazorati': 'Контроль исполнения',
    'Aloqalar grafi': 'Граф связей',
    Hisobotlar: 'Отчёты',
    Bildirishnoma: 'Уведомления',
    Bildirishnomalar: 'Уведомления',
    Qidirish: 'Поиск',
    'Til tanlash': 'Выбрать язык',
    Menyu: 'Меню',
    Saqlash: 'Сохранить',
    Yuborish: 'Отправить',
    Eksport: 'Экспорт',
    Tozalash: 'Очистить',
    Filter: 'Фильтр',
    'Qoralama saqlash': 'Сохранить черновик',
    'Bekor qilish': 'Отмена',
    'Davom etish': 'Продолжить',
    Orqaga: 'Назад',
    Keyingi: 'Далее',
    Tugatish: 'Завершить',
    'O‘tkazib yuborish': 'Пропустить',
    'Bo‘sh ro‘yxat': 'Пустой список',
    'Eksport formatini tanlang': 'Выберите формат экспорта',
    'Tafsilot drawer': 'Подробности',
    'Jadvaldan qidirish': 'Поиск по таблице',
    'ta yozuv': 'записей',
    'Filterlarni tozalash': 'Очистить фильтры',
    'Ma’lumot saqlandi': 'Данные сохранены',
    'Amal bajarildi': 'Действие выполнено',
    'Demo ma’lumotlar yangilandi.': 'Демо-данные обновлены.',
    'Forma tozalandi': 'Форма очищена',
    'Kiritilgan qiymatlar tozalandi.': 'Введённые значения очищены.',
    'Eksport tayyor': 'Экспорт готов',
    'Fayl yuklab olindi.': 'Файл загружен.',
    'Til almashtirildi': 'Язык изменён',
    'rejimi yoqildi.': 'режим включён.',
    'Yangi xabar': 'Новое сообщение',
    'Majlis sanasi': 'Дата заседания',
    'To‘lov holati': 'Статус оплаты',
    'Davlat boji tasdiqlandi.': 'Государственная пошлина подтверждена.',
    'Global qidiruv oynasi tayyorlanmoqda.': 'Глобальный поиск готовится.',
    'Tezkor komandalar paneli ochiladi.': 'Откроется панель быстрых команд.'
  }
};

const wordMaps = {
  en: {
    ariza: 'claim',
    arizalar: 'claims',
    sud: 'court',
    sudya: 'judge',
    fuqaro: 'citizen',
    yangi: 'new',
    va: 'and',
    uchun: 'for',
    bilan: 'with',
    orqali: 'through',
    'bo‘yicha': 'by',
    faol: 'active',
    holat: 'status',
    sana: 'date',
    qaror: 'decision',
    ishlar: 'cases',
    ish: 'case',
    hujjatlar: 'documents',
    hujjat: 'document',
    'to‘lov': 'payment',
    xavfsizlik: 'security',
    tizim: 'system',
    ochiq: 'public',
    reestr: 'registry',
    yaratish: 'create',
    tahrirlash: 'edit',
    boshqaruvi: 'management',
    boshqarish: 'manage',
    qidiruv: 'search',
    qidirish: 'search',
    'ma’lumot': 'information',
    'ma’lumotlar': 'information',
    'ro‘yxati': 'list',
    tafsilotlari: 'details',
    monitoring: 'monitoring',
    markazi: 'center',
    tomonlar: 'parties',
    kelishuv: 'settlement',
    kelishuvi: 'agreement',
    takliflari: 'proposals',
    sessiyalar: 'sessions',
    muvaffaqiyat: 'success',
    ehtimoli: 'probability',
    nizosi: 'dispute',
    mehnat: 'labor',
    oilaviy: 'family',
    iqtisodiy: 'economic',
    mediator: 'mediator',
    tayinlanmoqda: 'being assigned',
    mavjud: 'available',
    sozlamalari: 'settings',
    hisobot: 'report',
    foydalanuvchi: 'user',
    qonunlar: 'laws',
    dalillar: 'evidence',
    dalil: 'evidence',
    majlis: 'hearing',
    vaqt: 'time',
    natija: 'result',
    tasdiqlash: 'confirm',
    tekshirish: 'review',
    yuklash: 'upload',
    saqlash: 'save',
    yuborish: 'submit'
  },
  ru: {
    ariza: 'заявление',
    arizalar: 'заявления',
    sud: 'суд',
    sudya: 'судья',
    fuqaro: 'гражданин',
    yangi: 'новый',
    va: 'и',
    uchun: 'для',
    bilan: 'с',
    orqali: 'через',
    'bo‘yicha': 'по',
    faol: 'активный',
    holat: 'статус',
    sana: 'дата',
    qaror: 'решение',
    ishlar: 'дела',
    ish: 'дело',
    hujjatlar: 'документы',
    hujjat: 'документ',
    'to‘lov': 'оплата',
    xavfsizlik: 'безопасность',
    tizim: 'система',
    ochiq: 'открытый',
    reestr: 'реестр',
    yaratish: 'создать',
    tahrirlash: 'редактировать',
    boshqaruvi: 'управление',
    boshqarish: 'управлять',
    qidiruv: 'поиск',
    qidirish: 'поиск',
    'ma’lumot': 'данные',
    'ma’lumotlar': 'данные',
    'ro‘yxati': 'список',
    tafsilotlari: 'подробности',
    monitoring: 'мониторинг',
    markazi: 'центр',
    tomonlar: 'стороны',
    kelishuv: 'урегулирование',
    kelishuvi: 'соглашение',
    takliflari: 'предложения',
    sessiyalar: 'сессии',
    muvaffaqiyat: 'успех',
    ehtimoli: 'вероятность',
    nizosi: 'спор',
    mehnat: 'трудовой',
    oilaviy: 'семейный',
    iqtisodiy: 'экономический',
    mediator: 'медиатор',
    tayinlanmoqda: 'назначается',
    mavjud: 'доступен',
    sozlamalari: 'настройки',
    hisobot: 'отчёт',
    foydalanuvchi: 'пользователь',
    qonunlar: 'законы',
    dalillar: 'доказательства',
    dalil: 'доказательство',
    majlis: 'заседание',
    vaqt: 'время',
    natija: 'результат',
    tasdiqlash: 'подтвердить',
    tekshirish: 'проверить',
    yuklash: 'загрузить',
    saqlash: 'сохранить',
    yuborish: 'отправить'
  }
};

const latinToCyrillic = {
  a: 'а',
  b: 'б',
  d: 'д',
  e: 'е',
  f: 'ф',
  g: 'г',
  h: 'ҳ',
  i: 'и',
  j: 'ж',
  k: 'к',
  l: 'л',
  m: 'м',
  n: 'н',
  o: 'о',
  p: 'п',
  q: 'қ',
  r: 'р',
  s: 'с',
  t: 'т',
  u: 'у',
  v: 'в',
  x: 'х',
  y: 'й',
  z: 'з',
  G: 'Г',
  O: 'О',
  Sh: 'Ш',
  Ch: 'Ч',
  sh: 'ш',
  ch: 'ч',
  ng: 'нг',
  'o‘': 'ў',
  'g‘': 'ғ',
  'O‘': 'Ў',
  'G‘': 'Ғ'
};

const toCyrillic = (text) => {
  let output = text;
  for (const [latin, cyrillic] of Object.entries(latinToCyrillic).sort(
    (a, b) => b[0].length - a[0].length
  )) {
    output = output.replaceAll(latin, cyrillic);
  }
  return output;
};

const replaceWords = (text, locale) => {
  let output = text;
  for (const [word, translation] of Object.entries(wordMaps[locale] ?? {}).sort(
    (a, b) => b[0].length - a[0].length
  )) {
    output = output.replace(new RegExp(`\\b${word}\\b`, 'giu'), translation);
  }
  return output;
};

export const translateText = (text, locale = 'uz') => {
  if (typeof text !== 'string' || !text.trim() || locale === 'uz') return text;
  if (locale === 'uz-cyrl') return toCyrillic(text);

  let output = text;
  for (const [phrase, translation] of Object.entries(phraseMaps[locale] ?? {}).sort(
    (a, b) => b[0].length - a[0].length
  )) {
    output = output.replaceAll(phrase, translation);
  }
  return replaceWords(output, locale);
};

export const translateDeep = (value, locale = 'uz') => {
  if (typeof value === 'string') return translateText(value, locale);
  if (Array.isArray(value)) return value.map((item) => translateDeep(item, locale));
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, translateDeep(item, locale)])
    );
  }
  return value;
};
